add_newline = true
format = """
$time\
$status\
$username\
$directory\
$perl\
$ruby\
$python\
$golang\
$rust\
$php\
$nodejs\
$aws\
$git_branch$git_state$git_status\
$cmd_duration\
[î‚°](bg:none fg:prev_bg)\
\n$character"""

[time]
disabled = false
time_format = "%T"
style="bg:white fg:black"
format = '[ $time ]($style)'

[status]
disabled = false
symbol = "âœ˜"
style = "bg:red fg:white"
format = '[î‚°]($style fg:prev_bg)[ $symbol ]($style)'

[username]
disabled = false
show_always = false
style_root = "bg:green"
style_user = "bg:green"
aliases = {"root" = "âš¡"}
format = "[î‚°]($style fg:prev_bg)[ $user ]($style)"

[directory]
disabled = false
style = "bg:blue fg:white"
read_only_style = "bg:blue fg:white"
truncation_length = 3
truncation_symbol = "â€¦/"
format = "[î‚°]($style fg:prev_bg)[ $path([ $read_only]($read_only_style)) ]($style)"

[perl]
disabled = false
symbol = "ğŸª"
style = "bg:yellow fg:black"
format = "[î‚°]($style fg:prev_bg)[ $symbol ($version )]($style)"

[ruby]
disabled = false
symbol = "â™¦ï¸"
style = "bg:red fg:white"
format = "[î‚°]($style fg:prev_bg)[ $symbol ($version )]($style)"

[python]
disabled = false
symbol = "ğŸ"
style = "bg:yellow fg:white"
format = '[î‚°]($style fg:prev_bg)[ $symbol $pyenv_prefix($version )(\($virtualenv\) )]($style)'

[golang]
disabled = false
symbol = "ğŸ¹"
style = "bg:cyan fg:white"
format = "[î‚°]($style fg:prev_bg)[ $symbol ($version )]($style)"

[rust]
disabled = false
symbol = "ğŸ¦€"
style = "bg:black fg:white"
format = "[î‚°]($style fg:prev_bg)[ $symbol ($version )]($style)"

[php]
disabled = false
symbol = "ğŸ˜"
style = "bg:yellow fg:black"
format = "[î‚°]($style fg:prev_bg)[ $symbol ($version )]($style)"

[nodejs]
disabled = false
symbol = "îœ˜"
style = "bg:green fg:white"
format = "[î‚°]($style fg:prev_bg)[ $symbol ($version )]($style)"

[aws]
disabled = false
symbol = "â˜ï¸"
style = "bg:yellow fg:black"
format = '[î‚°]($style fg:prev_bg)[ $symbol ($profile )(\($region\) )]($style)'

[git_branch]
disabled = false
style = "bg:white fg:black"
symbol = "î‚ "
format = '[î‚°]($style fg:prev_bg)[ $symbol $branch ]($style)'

[git_state]
disabled = false
style = "bg:white fg:black"

[git_status]
disabled = false
style = "bg:white fg:black"
conflicted = 'ğŸš©'
stashed = 'ğŸ“¦'
modified = 'ğŸ“'
deleted = 'ğŸ—‘ï¸'
untracked = 'â“'
up_to_date = 'âœ”'
format = '[$all_status$ahead_behind ]($style)'

[cmd_duration]
disabled = false
min_time = 5000
style = "bg:yellow fg:black"
format = '[î‚°]($style fg:prev_bg)[ $duration ]($style)'
